#########################开发环境

############################################################
#
# Server 服务端相关配置
#
############################################################
server:
  port: 8084
  servlet:
    context-path: /kim
  tomcat:
    uri-encoding: UTF-8


spring:
  ############################################################
  #
  # 配置数据源相关	使用阿里巴巴的 druid 数据源
  #
  ############################################################
  #  mysql数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kimsohyun?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: kim
    password: kim
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet.allow: true

  ############################################################
  #
  # thymeleaf 静态资源配置
  #
  ############################################################
  thymeleaf:
    prefixL: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    # 关闭缓存, 即时刷新, 上线生产环境需要改为true
    cache: false

  ############################################################
  #
  # jpa参数配置
  #
  ############################################################
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true


############################################################
#
# mybatis 配置
#
############################################################
# mybatis 配置
mybatis:
  type-aliases-package: com.superc.kimsohyun.domain
  mapper-locations: com/superc/kimsohyun/mapper/*.xml

# 通用 Mapper 配置
#mapper:
#  mappers: com.imooc.utils.MyMapper
#  not-empty: false
#  dentity: MYSQL

# 分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

